# Generated by Django 2.2.28 on 2023-12-05 09:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_conditions', '0003_auto_20231204_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termandcondition',
            options={'verbose_name': 'Terms and Conditions', 'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.AlterField(
            model_name='termandcondition',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
