# Generated by Django 2.2.28 on 2023-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Client', 'Client'), ('Coach', 'Coach'), ('Coachee', 'Coachee')], default='Super Admin', max_length=30),
        ),
    ]
