# Generated by Django 2.2.28 on 2023-04-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'List of all feedback', 'verbose_name_plural': 'List of all feedbacks'},
        ),
    ]
