# Generated by Django 2.2.28 on 2023-04-15 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0008_auto_20230415_1037'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coachee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='coachee_profile_pictures/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachees', to='clients.Client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coachee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
