# Generated by Django 2.2.28 on 2023-04-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coachees', '0002_coachee_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachee',
            options={'verbose_name': 'List of all coachee', 'verbose_name_plural': 'List of all coachees'},
        ),
    ]
