# Generated by Django 2.2.28 on 2023-05-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_auto_20230419_2105'),
        ('coachees', '0003_auto_20230424_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sessions', models.IntegerField(default=0)),
                ('engagement_status', models.CharField(choices=[('start', 'Start Engagement'), ('end', 'End Engagement'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('coaching_status', models.CharField(choices=[('assigned', 'Assigned'), ('not_assigned', 'Not Assigned')], default='not_assigned', max_length=20)),
                ('is_chemistry_call', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_infos', to='coaches.Coach')),
                ('coachee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_infos', to='coachees.Coachee')),
            ],
            options={
                'verbose_name': 'EngagementInfo',
            },
        ),
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('call_type', models.CharField(choices=[('chemistry_call', 'Chemistry Call'), ('training', 'Training')], max_length=20)),
                ('engagement_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_sessions', to='coachees.EngagementInfo')),
            ],
            options={
                'verbose_name': 'CoachingSession',
            },
        ),
    ]
