# Generated by Django 2.2.28 on 2023-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachees', '0005_auto_20230527_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementinfo',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagementinfo',
            name='num_scheduled_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='session',
            name='call_type',
            field=models.CharField(choices=[('Chemistry Call', 'Chemistry Call'), ('Coaching Session', 'Coaching Session')], max_length=20),
        ),
    ]
