# Generated by Django 2.2.28 on 2023-05-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachees', '0006_auto_20230528_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementinfo',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagementinfo',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
