# Generated by Django 2.2.28 on 2023-08-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachees', '0007_auto_20230529_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(max_length=300)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachees.Session')),
            ],
        ),
        migrations.CreateModel(
            name='CoacheesReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_1', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rate_2', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rate_3', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rate_4', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(max_length=300)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachees.Session')),
            ],
        ),
    ]
