# Generated by Django 2.2.28 on 2023-08-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachees', '0008_coacheesreviews_coachreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachFinalReportReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_1', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rate_2', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rate_3', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rate_4', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(max_length=300)),
                ('engagement_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_final_report_review', to='coachees.EngagementInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CoacheesFinalReportReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_1', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rate_2', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rate_3', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('rate_4', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(max_length=300)),
                ('engagement_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachee_final_report_review', to='coachees.EngagementInfo')),
            ],
        ),
    ]
