# Generated by Django 2.2.28 on 2023-09-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachees', '0010_session_utc_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coacheesfinalreportreview',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='coacheesreviews',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='coachfinalreportreview',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='coachreviews',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
