# Generated by Django 2.2.28 on 2023-10-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coachees', '0012_auto_20231006_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_completed',
            new_name='is_notify',
        ),
    ]
