# Generated by Django 2.2.28 on 2023-10-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coachees', '0013_auto_20231014_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_reviewed_by_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='is_reviewed_by_coachee',
            field=models.BooleanField(default=False),
        ),
    ]
