# Generated by Django 2.2.28 on 2023-12-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coachees', '0014_auto_20231017_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_sid', models.CharField(max_length=300)),
                ('room_name', models.CharField(max_length=300)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coachees.Session')),
            ],
        ),
    ]
