# Generated by Django 2.2.28 on 2023-04-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230430_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='used_for_password_reset',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
