# Generated by Django 2.2.28 on 2023-04-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230430_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='valid_until',
        ),
    ]
