# Generated by Django 2.2.28 on 2023-04-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_auto_20230418_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'List of all coach', 'verbose_name_plural': 'List of all coaches'},
        ),
    ]
