# Generated by Django 2.2.28 on 2023-05-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_auto_20230419_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachavailability', to='coaches.Coach')),
            ],
        ),
    ]
