# Generated by Django 2.2.28 on 2023-09-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_coachavailability_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachavailability',
            name='utc_offset',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
