# Generated by Django 2.2.28 on 2024-03-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlytoken',
            name='access_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='calendlytoken',
            name='refresh_token',
            field=models.CharField(max_length=500),
        ),
    ]
