# Generated by Django 2.2.28 on 2024-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0003_auto_20240328_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendlytoken',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='calendlytoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
