# Generated by Django 2.2.28 on 2023-09-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='action_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
