# Generated by Django 2.2.28 on 2023-09-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationhistory_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
