# Generated by Django 2.2.28 on 2023-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationhistory_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='notification_name',
            field=models.CharField(max_length=100),
        ),
    ]
