# Generated by Django 2.2.28 on 2023-04-24 20:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy', '0001_privacy_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Privacy Policy', 'verbose_name_plural': 'Privacy Policies'},
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
